# Generated by Django 6.0.5 on 2026-05-25 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('celular', models.CharField(max_length=14)),
                ('tipo_usuario', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=10)),
                ('descricao_servico', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('R', 'Recebido'), ('A', 'A Caminho'), ('C', 'Concluído')], max_length=1)),
                ('data', models.DateField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borracharia.user')),
            ],
        ),
    ]
