# Generated by Django 6.0.5 on 2026-05-25 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borracharia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borracharia.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borracharia.user')),
            ],
        ),
    ]
